### ISSUE TITLE
Surf Ramps Are Bunched Up At 0,0,0

### ISSUE THREAD

**Issue by krakow10** [icewind1991/vbsp#6]
I am having the following issue, but only on specific maps:
![image](https://github.com/icewind1991/vbsp/assets/3529698/e379fb81-5f42-4ef6-add8-8d2037cd2b5c)
Here is the map file:
[surf_innokia.bsp](https://github.com/icewind1991/vbsp/files/14276815/surf_innokia.bsp.txt)

Is this an issue with my usage of the library?  Here is some relevant code:
```Rust
bsp.models().enumerate().map(|(mesh_id,world_model)|{

...

world_model.faces().enumerate().map(|(polygon_group_id,face)|{

...

face.vertex_positions().map(|vertex_position|{
```
https://git.itzana.me/StrafesNET/bsp_loader/src/commit/00df8288849f8da4a61ff96a9d3f7fc8e6162c2a/src/bsp.rs#L61
(MIT | Apache Licensed)

Which is a dependency of this project:
https://git.itzana.me/StrafesNET/strafe-client
(Copyright me, source available)

If you build the client, drag and drop the map onto the window or pass it as a command line argument to load it.  The map physics does not work for bsp maps as of the time of posting, hold E to hang in the air.

**Comment by krakow10** [comment]
Also happening on the tf2 map `ctf_turbine`:
![image](https://github.com/icewind1991/vbsp/assets/3529698/dfd5c20e-e804-440d-87a0-b812bf3fa086)

**Comment by icewind1991** [comment]
turbine is loading fine in [my viewer](https://github.com/icewind1991/vbspview)

![Screenshot_20240219_135746](https://github.com/icewind1991/vbsp/assets/1283854/79016e14-082b-4124-a664-b6a51b4b72f8)

You might be missing mesh/model positions somewhere

**Comment by icewind1991** [comment]
Depending on your use case you can maybe use [the gltf converter](https://github.com/icewind1991/vbsp-to-gltf) instead to remove the need to assembly the model parts yourself

**Comment by krakow10** [comment]
Some of the world models need additional data from elsewhere?  I thought it was just the props.  Thanks for the pointers, I didn't know about your viewer I'll investigate how that works and see if I can find the issue.

**Comment by krakow10** [comment]
Thanks for the tips!
![image](https://github.com/icewind1991/vbsp/assets/3529698/67657010-d95a-4caa-933f-c3443f6082c4)

Edit:
I'm coming back to this in the future and writing down more details.  The problem was that world model 0 is a baked version of the world designed for graphics only, with many faces not visible from the bsp culled.  However, within the same list there are additional models, but they are not meant to be used in the same way - they are used from entity brushes by model id with their own origin value.
